// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpXylBcq7GGDWPdG4gBxVnZRoEpfc5_28',
    appId: '1:1054303905004:web:6c9c46728cde3950d971c9',
    messagingSenderId: '1054303905004',
    projectId: 'shopping-app-123454321',
    authDomain: 'shopping-app-123454321.firebaseapp.com',
    storageBucket: 'shopping-app-123454321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55SepBD59gg6rDZSNIK1bsBfC3VaGukA',
    appId: '1:1054303905004:android:5b958e2537339e76d971c9',
    messagingSenderId: '1054303905004',
    projectId: 'shopping-app-123454321',
    storageBucket: 'shopping-app-123454321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlk9U01_twzeVYXhtO3oZwGUfFhnztXTU',
    appId: '1:1054303905004:ios:99959293fe3d6841d971c9',
    messagingSenderId: '1054303905004',
    projectId: 'shopping-app-123454321',
    storageBucket: 'shopping-app-123454321.appspot.com',
    iosClientId: '1054303905004-qllrklltf2rtqv1uq508lje00hr90ubq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingAppShaimaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlk9U01_twzeVYXhtO3oZwGUfFhnztXTU',
    appId: '1:1054303905004:ios:b950479c58a0371ad971c9',
    messagingSenderId: '1054303905004',
    projectId: 'shopping-app-123454321',
    storageBucket: 'shopping-app-123454321.appspot.com',
    iosClientId: '1054303905004-mvig8vak6s2le5mt06287786t9c6g9s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingAppShaimaa.RunnerTests',
  );
}
